### PR TITLE
1.12 Overhaul (Grid Generation, Docs, Bugfixes)

### LINKED ISSUE #399: Suggestion: OP private bypass
Suggestion to allow operators to access private machines.

### LINKED ISSUE #408: Exit machine teleported into results in exiting from wrong machine
[This is a fun one. found while playing ATM3-Remix on 1.12.2. I hope this is the right place to report it]

Scenario: Placing a teleporting device (I used Waystones for this) in a compact machine, with other provisions and equipment, and carrying the machine around while exploring to use as a mobile waypoint. (Machine A)

Have another compact machine back at the home base serving another utility function. (Machine B)

Enter, then exit machine B. Teleport into then exit machine A.

Expected result: Player is standing outside of machine A.
Actual result: Player is standing outside of machine B.

Possible fix: Add a list of "exit locations" for the player keyed off the machine id.

Difficulty for fixing: Any fix might conflict with implementing. https://github.com/thraaawn/CompactMachines/issues/148

(Great work on this mod, by the way.)

### LINKED ISSUE #413: Spectator mode boots me out of the dimension
**Compact Machines version**: compactmachines3-1.12.2-3.0.18-b278
**Forge version**: forge-1.12.2-14.23.5.2838-universal
**I am not using Optifine**: Correct.

**Description of the problem including expected versus actual behavior:**
So, I'm a server admin. I've been troubleshooting lag issues using LagGoggles, which has a function that teleports you directly to a specified Tile Entity. Unfortunately, this usually teleports you *into* blocks, because TEs are usually machines connected to pipes. And, usually, these are against the walls of the player's Compact Machines, which leaves me trapped.

Since I can't move, I don't know which coordinates to `/tp` to safely, and I don't want to break any blocks to free myself, as it might disrupt someone's setup that I don't know how to replace correctly. So I've attempted to use `/gamemode spectator` to get unstuck and take a look at the TE in question, but this boots me out of the dimension to my last overworld location.

I'm assuming this is a side effect of this config option?

```
  # Block players from leaving the Compact Machine they should currently be in [default: true]
    B:keepPlayersInside=true
```

But if that's the case, is there a way to allow only ops to bypass this, rather than setting it to false for everyone? I still want to ensure that my players don't accidentally glitch outside their machines and fall to their death.

Thanks for your time!

### LINKED ISSUE #429: 1.12.2 update to add 2-dimensional grid support for machine generation
I have tried contacting the mod creator, @thraaawn aka Davenonymous, on Discord and Twitter and have no received any word. I would like to release a new update to the mod that is mainly a huge Quality of Life feature update.

This update will mainly focus on turning the mod into a grid-based system instead of only operating on the x-axis. I have already refactored most of the codebase to work with this and am mainly in a bug-testing state. I also have made sure to make it **completely backwards-compatible** and am actively testing this compatability as well. So far it has worked with pretty good success. I have also refactored the config file and config GUI to have better localization and more comments on what each values do, along with making it look nicer in general. This update is in the works, but I am confident it will be a nice feature because a big drawback to the mod is the rendering issues that happen at millions of blocks out. On a large server, this is easy to get machines this far out and it is really detrimental to the player experience. I would also be happy to take over the project if thraaawn does not have the time to be able to update it. I hope this reaches the mod creator so that this update can get out to people. I would really enjoy having a conversation with the mod author. Currently, I am not experience much in Forge mod development but have many years of experience in plugin development and Java. Therefore, I am working mainly on server-based features that do not involve rendering so this update will not feature any new blocks/items. Please feel free to comment below.

### PR DESCRIPTION
**Pull request by SizableShrimp**
This is a backwards-compatible breaking change to how the 1.12.2 (Compact Machines 3) mod works. I have bumped the version to 3.1.0 to reflect this. Depending on what is decided to do with this PR, it could be the final 1.12.2 update before 1.16.4 is released.

I reviewed all the code I modified and have tested it in-game, but redundancy for testing is always good. I have been running this in production with a small server without issues, and the issues that have arose, I have fixed. There are some more recent changes I made in the last 24 hours that I haven't yet gotten to test specifically, but they are mainly just code refactors that don't change much actual logic of how the mod works. Here is a link to a compiled JAR for testing purposes: [Compact Machines 3.1.0](https://cdn.discordapp.com/attachments/718807454703550544/793217992090451998/compactmachines3-1.12.2-3.1.0.jar)

### Summary of changes
- **Add 2d grid generation**
- Support older 3.0.18 file formats
- Update build.gradle
- Manually include RS API
- Add /compactmachines3 documentation command
- Minor bug fixes
- Translation overhaul
- Logger refactoring
- and other stuff I have missed

A majority of the code refactoring was switching code dependent on `mod 1024` to its appropriate `roomPos` equivalent by getting the room position data from the `WorldSavedDataMachines`. The `roomPos` is the very northwest corner of the room at y=40. It is the corner of the machine wall box. The first one would generate at (0, 40, 0), and then it would populate the grid around (0, 0). The `roomPos` generation is backwards-compatible so that it doesn't overwrite old machine rooms. All changed NBT formats are also backwards-compatible in every single way that I could make possible. This means that any old save data on 3.0.18 will be seamlessly transferred to the newer format. Note that **this NBT data update is not reversible and save data is permanently altered**. This should be fine for most people, but "trying out" the newer mod version and then changing the mod back if you don't like it is not an option *unless* a backup is made. For the majority of users and modpack creators that are still on 1.12.2, this update should not negatively affect anything and should be a great plus for server owners (reasoning explained below). The room position of each room is displayed inside of the GUI of machine previews if users are admins. This allows for administrators to easily navigate to rooms if they need. The relevant teleportation commands still function and teleport admins to the correct room location. One weak point of CM3 is the poor command documentation and overall command structure. For example, it is not stated anywhere that doing `/compactmachines3 machines view (insert machine id here)` will display the specific machine id. This could be something to improve in a further PR.

## Reasoning for the change
For large servers, having ALL compact machines on *one dimensional axis* is very inefficient on server resources and fosters a bad user-graphical experience. Since every machine is generate in the form `(1024*machine id, 40, 0)`, this means that after only 499 generated machines, the 500th machine is located at `(512000, 40, 0)`. At this distance and further, many rendering bugs with Tile Entities and graphical mod displays appear. For example, the mod's own miniaturization field projectors sweeping monitor motion completely bugs out because of **floating-point rounding precision errors** that appear at large distances. The 1.12.2 Minecraft rendering engine (LWJGL 2) simply does not perform well with rendering Tile Entities and other things at large distances away from `(0, 0)`. By converting generation to a 2-dimensional system (and supporting backwards-compatibility for already-generated machines), immediate improvements can be seen on servers with many machines. All machines generated after updating from 3.0.18 to 3.1.0 are now generated in a 2-dimensional fashion starting from the origin. The format for a machine generated on 3.1.0 would now be `(512*x, 40, 512*y)` where `x` and `y` are dependent on the generation code and any existing older rooms. Any older machines would be converted to this new `roomPos` storage format as well. This means that any newly generated machines will immediately lose all rendering bugs and issues that appear on 3.0.18. The same 500 machines that generated out to `(512000, 40, 0)` in 3.0.18 could fit in an approximately 11,000 x 11,000 square in 3.1.0. This is nowhere near the amount of distance needed with only one dimension. These gains also improve with more generated machines since the perimeter of the square increases faster than its side length. This is my reasoning for making these large changes.

I hope this PR can be tested and accepted before the 1.16.4 version (Compact Machines 4) is released. I'd hate to see this work wasted when it brings so much improvements for 1.12.2 users and modpacks that still might want to incorporate the mod.

### CODE REVIEW

File: src/main/java/org/dave/compactmachines3/CompactMachines3.java [hunk 1]
```diff
@@ -7,39 +7,54 @@
...
+    public static final String VERSION = "@VERSION@";
     public static final String GUI_FACTORY = "org.dave.compactmachines3.misc.ConfigGuiFactory";
 
     @Mod.Instance(CompactMachines3.MODID)
     public static CompactMachines3 instance;
+    public static final Logger logger = LogManager.getLogger(CompactMachines3.MODID);
 
     public static ClientWorldData clientWorldData;
+    public static Map<Integer, BlockPos> clientMachineGrid;
+    public static Map<Integer, EnumMachineSize> clientMachineSizes;
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/CompactMachines3.java]: This seems a bit odd placed here; done in a WSD instance on the 1.16 version. Any particular reasoning?

File: src/main/java/org/dave/compactmachines3/block/BlockMachine.java [hunk 2]
```diff
@@ -227,15 +228,20 @@ public static void spawnItemWithNBT(World world, BlockPos pos, EnumMachineSize s
...
+        } else {
+            NBTTagCompound compound = new NBTTagCompound();
+            compound.setInteger("machineId", te.id);
+            if (te.hasOwner()) {
+                compound.setUniqueId("owner", te.getOwner());
+            }
+            if (te.hasNewSchema()) {
+                compound.setString("schema", te.getSchemaName());
+            }
+            stack.setTagCompound(compound);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/block/BlockMachine.java:243]: Possibly breaking change, did this config value exist before, or was it not documented?

File: src/main/java/org/dave/compactmachines3/block/BlockRedstoneTunnel.java [hunk 3]
```diff
@@ -81,16 +81,19 @@ public boolean onBlockActivated(World world, BlockPos pos, IBlockState state, En
...
 
-            int coords = StructureTools.getCoordsForPos(pos);
-            HashMap<EnumFacing, RedstoneTunnelData> sideMapping = WorldSavedDataMachines.INSTANCE.redstoneTunnels.get(coords);
-            while(sideMapping != null) {
+            int id = StructureTools.getIdForPos(pos);
+            Map<EnumFacing, RedstoneTunnelData> sideMapping = WorldSavedDataMachines.getInstance().redstoneTunnels.get(id);
+            if (sideMapping == null) {
+                return true;
+            }
+            while (true) {
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/block/BlockRedstoneTunnel.java:96]: Single null check over a long-running while loop, looks like?

File: src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java [hunk 4]
```diff
@@ -43,14 +43,14 @@ public void execute(MinecraftServer server, ICommandSender sender, String[] args
         }
 
         Schema schema = SchemaRegistry.instance.getSchema(args[0]);
-        int coords = StructureTools.getCoordsForPos(sender.getCommandSenderEntity().getPosition());
-        EnumMachineSize machineSize = WorldSavedDataMachines.INSTANCE.machineSizes.get(coords);
-        if(machineSize != schema.getSize()) {
-            throw this.getException(sender, "machine_size_does_not_match");
+        int id = WorldSavedDataMachines.getInstance().getMachineIdFromBoxPos(sender.getCommandSenderEntity());
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java]: I understand the intent from context, but `BoxPos` on a `PlayerEntity` instance is a bit misleading here

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java [hunk 5]
```diff
@@ -115,10 +114,10 @@ public String toString() {
 
     public boolean isPosInside(int x, int y) {
         boolean isInsideX = this.getActualX() <= x && x < this.getActualX() + this.width;
-        //Logz.info("[%s] insideX: %d < %d <= %d --> %s", this.id, this.lastDrawX, x, this.lastDrawX + this.lastDrawWidth, this.toString());
+        //Logz.info("[{}] insideX: {} < {} <= {} --> {}", this.id, this.lastDrawX, x, this.lastDrawX + this.lastDrawWidth, this.toString());
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java]: If these are commented out, better to remove the lines since they haven't been used in production for a while

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetButton.java [hunk 6]
```diff
@@ -63,7 +63,7 @@ public void setUnlocalizedLabel(String unlocalizedLabel) {
 
     @Override
     public void draw(GuiScreen screen) {
-        //Logz.info("Width: %d, height: %d", width, height);
+        //Logz.info("Width: {}, height: {}", width, height);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetButton.java]: Prefer full removal of unnecessary logging

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetInputField.java [hunk 7]
```diff
@@ -50,7 +50,7 @@ public WidgetInputField(String fieldIdentifier) {
         this.addListener(MouseClickEvent.class, new IWidgetListener<MouseClickEvent>() {
             @Override
             public WidgetEventResult call(MouseClickEvent event, Widget widget) {
-                //Logz.info("Mouse clicked @ x=%d, y=%d", event.x, event.y);
+                //Logz.info("Mouse clicked @ x={}, y={}", event.x, event.y);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetInputField.java]: Prefer full removal of unnecessary logging

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetList.java [hunk 8]
```diff
@@ -71,7 +71,7 @@ public void draw(GuiScreen screen) {
         Gui.drawRect(0, 0, width, height, borderColor);
         Gui.drawRect(1, 1, width-1, height-1, backgroundColor);
 
-        //Logz.info("Rendering lines %d to %d", lineOffset, lastVisibleLine);
+        //Logz.info("Rendering lines {} to {}", lineOffset, lastVisibleLine);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetList.java]: Prefer full removal of unnecessary logging

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java [hunk 9]
```diff
@@ -21,7 +21,7 @@ public WidgetPanel() {
         // Also notify widgets when the mouse entered or exited their area
         this.addListener(MouseMoveEvent.class, (event, widget)-> {
 
-            //Logz.info("[%s] Moved mouse to x=%d, y=%d", widget.id, innerX, innerY);
+            //Logz.info("[{}] Moved mouse to x={}, y={}", widget.id, innerX, innerY);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java]: Prefer full removal of unnecessary logging

File: src/main/java/org/dave/compactmachines3/gui/psd/Page.java [hunk 10]
```diff
@@ -33,10 +35,10 @@ public void draw(GuiPSDScreen guiPSDScreen, FontRenderer fontRenderer, RenderIte
 
     public void mouseClicked(GuiPSDScreen psd, int mouseX, int mouseY, int mouseButton) {
         if(mouseButton == 1) {
-            if(name == "welcome") {
+            if(name.equals("welcome")) {
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/psd/Page.java:38]: Should probably leave the `==` check here, and maybe consider moving the value to a const somewhere..

File: src/main/java/org/dave/compactmachines3/CompactMachines3.java (hunk 1 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/CompactMachines3.java]: No particular reason; I mainly did it since there is another client-side field that used the main mod class for this even though it is quite improper. I can move this to the WSD class once I get home. Collaborators also have access to push commits to my fork if you care enough to do it yourself.

File: src/main/java/org/dave/compactmachines3/block/BlockMachine.java (hunk 2 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/block/BlockMachine.java:243]: It did not exist before. I added it, but it defaults to false so as to explicitly not cause breaking changes. I refactored the config a bit, mainly adding more language key translations and some refactoring. You can find these changes in the `ConfigurationHandler` class I believe.

File: src/main/java/org/dave/compactmachines3/block/BlockRedstoneTunnel.java (hunk 3 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/block/BlockRedstoneTunnel.java:96]: This loop is weird. I didn't investigate it much, but IntelliJ notified me that the `sideMapping` can only be null once since it is not updated inside the loop. I'm not sure what the loop is doing, but I'd rather not change something I don't understand.

File: src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java (hunk 4 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java]: I think what I was going for with `BoxPos` was "a position inside the box", which an entity could be considered a position. If you have a better name for this overloaded method, feel free to tell me.

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java (hunk 5 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java]: Sure. I mainly left them since they were there before. I was using a search and replace function to replace al the string formats with logger formats. I can remove them when I get home.

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetButton.java (hunk 6 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetButton.java]: Noted

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetInputField.java (hunk 7 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetInputField.java]: Noted

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetList.java (hunk 8 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetList.java]: Noted

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java (hunk 9 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java]: Noted

File: src/main/java/org/dave/compactmachines3/gui/psd/Page.java (hunk 10 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/gui/psd/Page.java:38]: `==` check?? It's a String....

File: src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipes.java [hunk 11]
```diff
@@ -46,9 +45,10 @@ public static MultiblockRecipe tryCrafting(World world, BlockPos projectorPos, I
     }
 
     public static MultiblockRecipe getRecipeByName(String name) {
-        Optional<MultiblockRecipe> opt = recipes.stream().filter(recipe -> recipe.getName().equals(name)).findFirst();
-        if(opt.isPresent()) {
-            return opt.get();
+        for (MultiblockRecipe recipe : recipes) {
+            if (recipe.getName().equals(name)) {
+                return recipe;
+            }
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipes.java:51]: Performance change?

Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipes.java:51]: ? Streams are slower than their imperative counterpart.

File: src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipe.java [hunk 12]
```diff
@@ -159,7 +160,7 @@ public void setPositionMap(String[][][] map) {
                         continue;
                     }
 
-                    referenceCount.put(content, referenceCount.getOrDefault(content, 0)+1);
+                    referenceCount.merge(content, 1, Integer::sum);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipe.java:163]: Assuming this is an automated update from Java 8?

Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipe.java:163]: Not automated, no. I manually modified this once I saw it was not using the proper solution since I was in that file for some other reason and it caught my eye.

File: src/main/java/org/dave/compactmachines3/CompactMachines3.java (hunk 1 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/CompactMachines3.java]: Fixed

File: src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java (hunk 4 above)
Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/command/CommandSchemaLoad.java]: I have updated this method to be called `getMachineIdFromEntityPos` for the entity overload method.

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java [hunk 13]
```diff
@@ -234,7 +231,7 @@ public void drawBeforeShift(GuiScreen screen) {
      * @param screen
      */
     public void draw(GuiScreen screen) {
-        //Logz.debug("Drawing widget: %s, x=%d, y=%d, width=%d, height=%d", this, layoutResult.getX(), layoutResult.getY(), layoutResult.getWidth(), layoutResult.getHeight());
+        //Logz.debug("Drawing widget: {}, x={}, y={}, width={}, height={}", this, layoutResult.getX(), layoutResult.getY(), layoutResult.getWidth(), layoutResult.getHeight());
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/Widget.java]: Needs removed instead of commented out

File: src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java [hunk 14]
```diff
@@ -47,19 +46,17 @@ public WidgetPanel() {
         this.addListener(MouseClickEvent.class, ((event, widget) -> {
             int innerX = event.x - widget.getActualX();
             int innerY = event.y - widget.getActualY();
-            //Logz.info("%s: Click: screen@%d,%d, panel@%d,%d", this.toString(), event.x, event.y, innerX, innerY);
+            //Logz.info("{}: Click: screen@{},{}, panel@{},{}", this.toString(), event.x, event.y, innerX, innerY);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/gui/framework/widgets/WidgetPanel.java]: Needs removed instead of commented out

File: src/main/java/org/dave/compactmachines3/misc/PlayerEventHandler.java [hunk 15]
```diff
@@ -166,29 +167,29 @@ public static void onPlayerTick(TickEvent.PlayerTickEvent event) {
             return;
         }
 
-        if(!ConfigurationHandler.MachineSettings.keepPlayersInside) {
+        if (enteredMachineId != -1 && lastId != enteredMachineId && ConfigurationHandler.MachineSettings.allowEnteringWithoutPSD) {
+            TeleportationTools.addMachineIdToHistory(enteredMachineId, event.player);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/misc/PlayerEventHandler.java:171]: Solves major issues with other mod teleportation (#408 in particular)

File: src/main/java/org/dave/compactmachines3/misc/PlayerEventHandler.java [hunk 16]
```diff
@@ -166,29 +167,29 @@ public static void onPlayerTick(TickEvent.PlayerTickEvent event) {
...
+        EnumMachineSize enumSize = WorldSavedDataMachines.getInstance().machineSizes.get(lastId);
         if(enumSize == null) {
             // This should only happen after someone updated before this feature was implemented:
             // The size value will only be known once at least one player entered the machine.
             // Handle this gracefully by doing nothing
             return;
         }
 
-        if(event.player.isCreative() && event.player.canUseCommand(2, "")) {
+        if((event.player.isCreative() || event.player.isSpectator()) && event.player.canUseCommand(2, "")) {
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/misc/PlayerEventHandler.java:187]: Resolves #413

File: src/main/java/org/dave/compactmachines3/tile/TileEntityFieldProjector.java [hunk 17]
```diff
@@ -368,7 +363,7 @@ public void update() {
             // Remove blocks from the world
             for(BlockPos pos : getInsideBlocks()) {
                 world.setBlockToAir(pos);
-                ((WorldServer)world).spawnParticle(EnumParticleTypes.SMOKE_LARGE, pos.getX(), pos.getY(), pos.getZ(), 10, 0.5D, 0.5D, 0.5D, 0.01D, new int[0]);
+                ((WorldServer)world).spawnParticle(EnumParticleTypes.SMOKE_LARGE, pos.getX(), pos.getY(), pos.getZ(), 10, 0.5D, 0.5D, 0.5D, 0.01D);
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/tile/TileEntityFieldProjector.java:366]: Why the removal of the int array here?

Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/tile/TileEntityFieldProjector.java:366]: The method was obviously generated by autocomplete. It's a varargs array and omitting it is more idiomatic.

File: src/main/java/org/dave/compactmachines3/world/WorldSavedDataMachines.java [hunk 18]
```diff
@@ -1,131 +1,198 @@
...
+        wsd.markDirty();
         return val;
     }
 
     public WorldSavedDataMachines(String name) {
         super(name);
     }
 
-    @SubscribeEvent
+    @SubscribeEvent(priority = EventPriority.HIGHEST)
```
Comment (robotgryphon) [inline src/main/java/org/dave/compactmachines3/world/WorldSavedDataMachines.java:167]: Why the priority increase?

Comment (SizableShrimp) [reply src/main/java/org/dave/compactmachines3/world/WorldSavedDataMachines.java:167]: Not sure, probably just to load the WSDM as soon as possible so as to avoid other race conditions. Probably an unnecessary change.
